name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: I'd like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: Currently, users face...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: The feature would work by...
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Provide a concrete example of how this feature would be used
      placeholder: |
        Example scenario:
        User wants to: [describe]
        Feature enables: [describe]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: I've also considered...

  - type: checkboxes
    id: type
    attributes:
      label: Feature Type
      description: What type of contribution is this?
      options:
        - label: New Agent Skill
        - label: New Prompt Template
        - label: New Custom Agent
        - label: New Instructions File
        - label: Enhancement to existing customization
        - label: Documentation improvement
        - label: Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: Here are some additional details...

  - type: checkboxes
    id: contribute
    attributes:
      label: Willingness to Contribute
      description: Can you help implement this?
      options:
        - label: I'd be willing to implement this feature
        - label: I'd need help implementing this
        - label: I'm just suggesting the idea

